[package]
name = "blog-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
blog-client = {path = "../blog_client"}
clap = { version = "4.5.54", features = ["derive"] }
dotenvy = {workspace = true}
anyhow = {workspace = true}
tokio = {workspace = true}
